[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version"

[build]
  publish = "docs/.vitepress/dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx nuxi prepare playground && npm run docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
