name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Typecheck
        run: pnpm run test:types

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Environment Variables
        run: cp playground/.env.example playground/.env

      - name: Install
        run: pnpm install

      - name: Build type stubs
        run: pnpm dev:prepare

      - name: Test
        run: pnpm run test
